# Generated by Django 4.1.5 on 2023-01-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='omega_dbconn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUSTOM_CODE', models.CharField(max_length=20)),
                ('CUSTOM_NAME', models.CharField(max_length=100)),
                ('VAT_RATE', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
