# Generated by Django 4.1.5 on 2023-01-24 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='omega_dbconn',
            name='VAT_RATE',
        ),
    ]
